export const UI = {
    // Navigation
    HOME: 'Inicio',
    LEARNING: 'Aprendizaje',
    PRACTICE: 'Práctica',
    LOGOUT: 'Cerrar sesión',
    LOGIN: 'Iniciar sesión',
    REGISTER: 'Registrarse',
    LOGIN_BUTTON: 'Iniciar sesión',
    REGISTER_BUTTON: 'Crear cuenta',

    // Auth
    EMAIL: 'Correo electrónico',
    PASSWORD: 'Contraseña',
    USERNAME: 'Nombre de usuario',
    CONFIRM_PASSWORD: 'Confirmar contraseña',
    PWD_LENGTH: '8+ caracteres (sin contar espacios)',
    PWD_UPPERCASE: 'Una mayúscula',
    PWD_NUMBER: 'Un número',
    PWD_SPECIAL: 'Un carácter especial (!@#$%^&*)',
    NO_ACCOUNT: '¿No tienes cuenta?',
    HAVE_ACCOUNT: '¿Ya tienes cuenta?',

    // Editor
    NEW_PROJECT: 'Nuevo proyecto',
    NEW_FILE: 'Nuevo archivo',
    OPEN_FILE: 'Abre un archivo para empezar',
    SAVE_HINT: 'Ctrl+S para guardar',
    UNSAVED: 'Sin guardar',
    SAVED: 'Guardado',
    CONNECTED: 'Conectado',
    RUN: 'Ejecutar',
    RUNNING: 'Ejecutando...',
    CURRENT: 'Actual',
    SAVED_PROJECTS: 'Proyectos guardados',
    NO_SAVED_PROJECTS: 'No hay proyectos guardados',
    CREATE_PROJECT_START: 'Crea un proyecto para empezar',
    NEW_PROJECT_BUTTON: '+ Nuevo Proyecto',

    // File tree
    CREATE_PROJECT: 'Crear proyecto',
    PROJECT_NAME: 'Nombre del proyecto',
    CANCEL: 'Cancelar',
    DELETE_PROJECT: 'Eliminar proyecto',
    DELETE_CONFIRM: 'Esto eliminará permanentemente',
    DELETE_WARNING: 'Esta acción no se puede deshacer.',
    COULD_NOT_DELETE: 'No se pudo eliminar el proyecto. Intenta de nuevo.',

    // AI Panel
    AI_TUTOR: 'Tutor IA',
    AI_WELCOME: 'Hola, soy tu tutor de programación',
    AI_SUBTITLE: 'Escribe un mensaje o analiza tu código',
    ANALYZE_CODE: 'Analizar',
    ANALYZING: 'Analizando...',
    NEXT_STEP_QUESTION: '¿Qué sigue?',
    EXPLAIN_THIS: 'Explícame esto',
    ASK_PLACEHOLDER: 'Escribe un mensaje...',
    CHAT: 'Chat',
    HISTORY: 'Historial',
    CODE_QUALITY: 'CALIDAD DEL CÓDIGO',
    WHAT_IT_DOES: 'QUÉ HACE TU CÓDIGO',
    SUGGESTIONS: 'SUGERENCIAS',
    NO_CONVERSATIONS: 'No hay conversaciones anteriores.',
    EXPLAIN_CODE_HINT: 'Presiona Ctrl+K para explicar',
    EXPLAINING: 'Explicando...',
    PREVIOUS_CONVERSATION: 'Conversación anterior',

    // Learning
    COURSES: 'Cursos',
    SEARCH_TOPICS: 'Buscar temas...',
    OVERALL_PROGRESS: 'Progreso general',
    CHOOSE_TOPIC: 'Elige un tema para comenzar',
    SELECT_TOPIC: 'Selecciona cualquier tema del menú lateral',
    NEXT: 'Siguiente',
    PREVIOUS: 'Anterior',
    COMPLETE_LESSON: 'Completar lección',
    SECTION_OF: 'Sección',
    OF: 'de',
    COMPLETED: 'Completado',
    IN_PROGRESS: 'En progreso',
    START: 'Comenzar',
    CONTINUE: 'Continuar',
    REVIEW: 'Repasar',
    LANGUAGES: 'Idiomas',
    PRACTICE_EDITOR: 'Practicar en el editor',

    // Levels
    BEGINNER: 'Principiante',
    INTERMEDIATE: 'Intermedio',
    ADVANCED: 'Avanzado',
    BEGINNER_DESC: 'Empieza desde cero. Sin experiencia necesaria.',
    INTERMEDIATE_DESC: 'Lleva tus habilidades al siguiente nivel.',
    ADVANCED_DESC: 'Domina conceptos complejos y patrones.',
    CHOOSE_LEVEL: 'Elige tu nivel',
    LESSONS_COUNT: 'lecciones',
    COMPLETE_FIRST: 'Completa',
    FIRST: 'primero',
    CONTINUE_REVIEWING: 'Seguir repasando',
    RESTART_LEVEL: 'Reiniciar nivel',
    RESTART_FROM_BEGINNING: 'Reiniciar desde el principio',
    RESTART_CONFIRM_TITLE: '¿Reiniciar nivel',
    RESTART_CONFIRM_DESC: 'Esto reiniciará tu progreso del nivel',
    RESTART_CONFIRM_ACTION: 'Sí, reiniciar desde la lección 1',
    LEVEL_COMPLETE: 'completado',
    YOU_COMPLETED: 'Completaste todas las lecciones de',
    PLUS_XP: '+100 XP',
    PRACTICE_WHAT_YOU_LEARNED: 'Practica lo que aprendiste',
    YOU_MASTERED: 'Dominaste',
    NEXT_LEVEL: 'Siguiente nivel',
    CONTINUE_TO: 'Continuar a',
    NO_CONTENT: 'No hay contenido disponible para esta lección.',

    // Exercise
    OPEN_IN_EDITOR: 'Abrir en editor',
    SHOW_HINT: 'Ver pista',
    ALL_HINTS_SHOWN: 'Todas las pistas mostradas',
    HINTS_LEFT: 'pistas restantes',
    HINTS_REVEALED: 'pistas reveladas',
    COPY_CODE: 'Copiar código',
    AI_REVIEWING: 'La IA está revisando tu código...',
    VERIFY_WITH_AI: 'Verificar con IA',
    VERIFYING: 'Verificando...',
    GREAT_WORK: '¡Buen trabajo!',
    KEEP_GOING: '¡Sigue intentando!',
    TRY_AGAIN: 'Intentar de nuevo',
    COULD_NOT_VERIFY: 'No se pudo verificar tu solución. Intenta de nuevo.',
    RESET: 'Restablecer',
    WRITE_SOLUTION: 'Escribe tu solución aquí...',
    VERIFY_ERROR: 'Error al verificar',
    THINGS_TO_IMPROVE: 'Cosas a mejorar:',
    NEXT_SECTION: 'Siguiente sección',
    STUDENT_SOLUTION: 'Lesson exercise',
    LESSON_EXERCISE: 'Ejercicio de la lección',

    // Console
    TERMINAL: 'Terminal',
    OUTPUT: 'Salida',
    PROBLEMS: 'Problemas',
    CLEAR: 'Limpiar',
    RUN_TO_SEE: 'Ejecuta tu código para ver la salida aquí',
    NO_PROBLEMS: 'No se detectaron problemas',

    // Errors
    ERROR_GENERIC: 'Ocurrió un error. Intenta de nuevo.',
    ERROR_CONNECTION: 'Error de conexión',
    ERROR_NOT_FOUND: 'No encontrado',
    RETRY: 'Reintentar',
    INCORRECT_CREDENTIALS: 'Correo o contraseña incorrectos',
    ACCOUNT_LOCKED: 'Cuenta bloqueada. Intenta en 15 minutos.',
    LOGIN_ERROR: 'Error al iniciar sesión. Intenta de nuevo.',
    REGISTER_ERROR: 'Error al registrarse. Intenta de nuevo.',

    // Toast
    PROJECT_SAVED: 'Proyecto guardado',
    PROJECT_CREATED: 'Proyecto creado',
    PROJECT_DELETED: 'Proyecto eliminado',
    FILE_CREATED: 'Archivo creado',
    FILE_DELETED: 'Archivo eliminado',
    COPIED: 'Copiado al portapapeles',
    WELCOME_BACK: '¡Bienvenido de vuelta!',
    ACCOUNT_CREATED: '¡Cuenta creada!',

    // Dark mode
    DARK_MODE: 'Modo oscuro',
    LIGHT_MODE: 'Modo claro',

    // Home
    AI_POWERED_TUTOR: 'Tutor de programación con IA',
    TAGLINE: 'Aprende a programar con un tutor inteligente a tu lado',
    DESCRIPTION: 'La IA analiza tu código en tiempo real, explica qué hace y sugiere los siguientes pasos. No da respuestas — aprendes haciendo.',
    START_PRACTICING: 'Empezar a practicar →',
    EXPLORE_COURSES: 'Explorar cursos',
    CHOOSE_MODE: 'Elige tu modo',
    MODE_AI_EDITOR: 'Editor IA',
    MODE_PRACTICE_DESC: 'Escribe código libremente. La IA analiza cada función en tiempo real, explica qué hace y sugiere los siguientes pasos sin resolverlo por ti.',
    MODE_LEARNING: 'Aprendizaje',
    MODE_LEARNING_DESC: 'Aprende desde cero con lecciones cortas y claras. Desde tu primer lenguaje hasta estructuras de datos, patrones de diseño y buenas prácticas.',
    FEATURE_REALTIME: 'Análisis en tiempo real',
    FEATURE_REALTIME_DESC: 'Detecta funciones y bloques mientras escribes, sin necesidad de ejecutar el código.',
    FEATURE_TUTOR: 'Tutor, no generador',
    FEATURE_TUTOR_DESC: 'Guía y explica en cada paso, pero nunca escribe el proyecto por ti.',
    FEATURE_SAVED: 'Progreso guardado',
    FEATURE_SAVED_DESC: 'Tus lecciones y proyectos completados se guardan para que puedas continuar cuando quieras.',
    GO_TO_EDITOR: 'Ir al editor →',
    EXPLORE_COURSES_ALT: 'Explorar cursos →',

    // Tooltips
    USER_MENU: 'Menú de usuario',
    SIGN_OUT: 'Cerrar sesión',
    COLLAPSE: 'Contraer',
    EXPAND: 'Expandir',
    DISMISS: 'Descartar',
    CLOSE: 'Cerrar',

    // Status
    BACKEND_STARTING: 'El servidor está iniciando, esto puede tomar 30 segundos...',
    BACKEND_OFFLINE_TITLE: 'No se puede conectar al servidor',
    BACKEND_OFFLINE_DESC: 'Verifica tu conexión e inténtalo de nuevo.',
    LOADING_PROJECT: 'Cargando proyecto...',
    LOADING_LESSON: 'Cargando lección...',
    PREPARING_EXERCISE: 'Preparando tu ejercicio...',
    REDIRECTING: '¡Cuenta creada! Redirigiendo...',
    SAVING: 'Guardando...',

    // Keyboard hints
    KB_SAVE: 'Ctrl+S Guardar',
    KB_RUN: 'Ctrl+Enter Ejecutar',
    KB_ANALYZE: 'Ctrl+Shift+A Analizar',
} as const
